jwt:
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_LINK:localhost:5432}/postgres
    password: ${DATABASE_PASSWORD:1234}
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.yandex.ru
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    username: JustForJunior@yandex.ru
    password: lxuchfpanzsoyius
    protocol: smtp