jwt:
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    password: ${DB_PASSWORD:1234}
    username: ${DB_USER:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: smtp.yandex.ru
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    username: JustForJunior@yandex.ru
    password: lxuchfpanzsoyius
    protocol: smtp